### ISSUE TITLE
elevate zoom breaks down when used with swiper

### ISSUE THREAD

**Issue by seunlanlege** [elevateweb/elevatezoom#138]
So im trying to make a desktop gallery with elevate zoom support

`<!DOCTYPE html>`
`<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Swiper demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">`
    
    `<link rel="stylesheet" href="../dist/css/swiper.min.css">
`
    
   `<style>`
   `html, body {
        position: relative;
        height: 100%;
    }`
    `body {
        background: #000;
        font-family: Helvetica Neue, Helvetica, Arial, sans-serif;
        font-size: 14px;
        color:#fff;
        margin: 0;
        padding: 0;
    }`
    `.swiper-container {
        width: 100%;
        height: 300px;
        margin-left: auto;
        margin-right: auto;
    }`
 `.swiper-slide {
        background-size: cover;
        background-position: center;
    }`
   `.gallery-top {
        height: 80%;
        width: 100%;
    }`
    `.gallery-thumbs {
        height: 20%;
        box-sizing: border-box;
        padding: 10px 0;
    }`
   `.gallery-thumbs .swiper-slide {
        width: 25%;
        height: 100%;
        opacity: 0.4;
    }`
    `.gallery-thumbs .swiper-slide-active {
        opacity: 1;
    }`

   `</style>`
`</head>
<body>``
    
`<div class="swiper-container gallery-top">`
`<div class="swiper-wrapper">`
`  <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
            <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
            <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
            <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
            <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
            <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
            <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
            <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
            <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
            <div class="swiper-slide"><img id="seun" data-zoom-image="SEUN.jpg" style="display:block;width:430px;height:100%;margin-left:auto;margin-right:auto;" src="SEUN.jpg"></div>
        </div>`
        
`<div class="swiper-button-next swiper-button-white"></div>`
`<div class="swiper-button-prev swiper-button-white"></div>`
` </div>
    <div class="swiper-container gallery-thumbs">`
`<div class="swiper-wrapper">
            <div class="swiper-slide seun"></div>
            <div class="swiper-slide seun"></div>
            <div class="swiper-slide seun"></div>
            <div class="swiper-slide seun"></div>
            <div class="swiper-slide seun"></div>
            <div class="swiper-slide seun"></div>
            <div class="swiper-slide seun"></div>
            <div class="swiper-slide seun"></div>
            <div class="swiper-slide seun"></div>
            <div class="swiper-slide seun"></div>
        </div>`
` </div>`
` <script src='jquery-1.8.3.min.js'></script>
    <script src='jquery.elevatezoom.js'></script>
    
    <script src="../dist/js/swiper.min.js"></script>
`
    
`<script>
    var galleryTop = new Swiper('.gallery-top', {
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        spaceBetween: 1,
    });
    var galleryThumbs = new Swiper('.gallery-thumbs', {
        spaceBetween: 1,
        centeredSlides: true,
        slidesPerView: 'auto',
        touchRatio: 0.2,
        slideToClickedSlide: true
    });
    galleryTop.params.control = galleryThumbs;
    galleryThumbs.params.control = galleryTop;
    $('#seun').elevateZoom({
    zoomType: "window",
    cursor: "crosshair",
    zoomWindowFadeIn: 500,
    zoomWindowFadeOut: 750
   });

</script>`
</body>
</html>
`

for some reason zoom support only works for the first image, fails for the rest.

**Comment by buyfie** [comment]
- 

- [ ] 

1.
